### ISSUE TITLE
Express Js 

### ISSUE THREAD

**Issue by pawelszczerbicki** [nobrainr/typescript-webpack-starter#13]
Hello,
I'm using your starter on my new project. How to integrate this with expressjs ?

**Comment by emyann** [comment]
Hello @pawelszczerbicki !  

Thank you for trying the starter! 🙏  Did you use the CLI to scaffold your project ? There is a `webpack-dev-server` provided out-of-the box. 
If you want to integrate `expressJs` with `webpack-dev-server` you need to actually add `webpack-dev-middleware`. Here are some resources that could help you https://stackoverflow.com/questions/31102035/how-can-i-use-webpack-with-express 

Let me know if it suits your need! 👍🏽

**Comment by emyann** [comment]
Closing this due to the inactivity of the thread :)
